version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    networks:
      - secshop-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    networks:
      - secshop-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/secureshop
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - secshop-network
    volumes:
      - mongodb_data:/data/db

networks:
  secshop-network:
    driver: bridge

volumes:
  mongodb_data:
